/* Generated by the bounded public-board discovery pass on 2026-08-30.
 * Every entry had at least one posting inside the 90-day freshness window.
 * Company names come from Greenhouse's own company_name field.
 */
export const HUNDRED_THOUSAND_FLOOR_DISCOVERY = [
  {
    "company_name": "Esri",
    "board_token": "esri",
    "fresh_jobs": 432
  },
  {
    "company_name": "Luminis Health",
    "board_token": "luminishealth",
    "fresh_jobs": 428
  },
  {
    "company_name": "DH Pace",
    "board_token": "dhpace",
    "fresh_jobs": 408
  },
  {
    "company_name": "Soho House & Co.",
    "board_token": "sohohouseco",
    "fresh_jobs": 401
  },
  {
    "company_name": "VitalCaring Group",
    "board_token": "vitalcaringgroup",
    "fresh_jobs": 395
  },
  {
    "company_name": "SumUp",
    "board_token": "sumup",
    "fresh_jobs": 394
  },
  {
    "company_name": "The Scion Group",
    "board_token": "thesciongroupllc",
    "fresh_jobs": 394
  },
  {
    "company_name": "INFUSE",
    "board_token": "infuse",
    "fresh_jobs": 387
  },
  {
    "company_name": "Nebius",
    "board_token": "nebius",
    "fresh_jobs": 374
  },
  {
    "company_name": "CFO Insights",
    "board_token": "cfoinsights",
    "fresh_jobs": 373
  },
  {
    "company_name": "Holder Construction",
    "board_token": "holderconstruction",
    "fresh_jobs": 369
  },
  {
    "company_name": "United Media",
    "board_token": "unitedmedia",
    "fresh_jobs": 367
  },
  {
    "company_name": "House Buyers of America",
    "board_token": "housebuyersofamerica",
    "fresh_jobs": 354
  },
  {
    "company_name": "Monks",
    "board_token": "monks",
    "fresh_jobs": 354
  },
  {
    "company_name": "Morgan & Morgan, P.A.",
    "board_token": "morganmorganjobsapplynow",
    "fresh_jobs": 353
  },
  {
    "company_name": "The N2 Company",
    "board_token": "n2publishingglassdoor",
    "fresh_jobs": 351
  },
  {
    "company_name": "Olsson",
    "board_token": "olsson",
    "fresh_jobs": 343
  },
  {
    "company_name": "OKX",
    "board_token": "OKX",
    "fresh_jobs": 341
  },
  {
    "company_name": "Zipline",
    "board_token": "flyzipline",
    "fresh_jobs": 326
  },
  {
    "company_name": "TEGNA Inc.",
    "board_token": "tegnainc",
    "fresh_jobs": 311
  },
  {
    "company_name": "On",
    "board_token": "onrunning",
    "fresh_jobs": 307
  },
  {
    "company_name": "DIG INN Chefs-In-Training",
    "board_token": "diginnother",
    "fresh_jobs": 306
  },
  {
    "company_name": "Canonical",
    "board_token": "canonical",
    "fresh_jobs": 303
  },
  {
    "company_name": "Picnic",
    "board_token": "teampicnic",
    "fresh_jobs": 301
  },
  {
    "company_name": "AvePoint",
    "board_token": "avepoint",
    "fresh_jobs": 300
  },
  {
    "company_name": "Veterinary Practice Partners",
    "board_token": "veterinarypracticepartners",
    "fresh_jobs": 295
  },
  {
    "company_name": "Power Digital",
    "board_token": "powerdigitalmarketing",
    "fresh_jobs": 290
  },
  {
    "company_name": "ConvenientMD",
    "board_token": "convenientmd",
    "fresh_jobs": 288
  },
  {
    "company_name": "HRtechX",
    "board_token": "hrtechx",
    "fresh_jobs": 287
  },
  {
    "company_name": "Mineralys Therapeutics",
    "board_token": "mineralystherapeutics",
    "fresh_jobs": 284
  },
  {
    "company_name": "Retail Insights",
    "board_token": "retailinsights",
    "fresh_jobs": 281
  },
  {
    "company_name": "Agoda",
    "board_token": "agoda",
    "fresh_jobs": 280
  },
  {
    "company_name": "Loenbro",
    "board_token": "loenbro",
    "fresh_jobs": 279
  },
  {
    "company_name": "Charlie Health",
    "board_token": "charliehealth",
    "fresh_jobs": 274
  },
  {
    "company_name": "CoreWeave",
    "board_token": "coreweave",
    "fresh_jobs": 271
  },
  {
    "company_name": "Revolution Medicines",
    "board_token": "revolutionmedicines",
    "fresh_jobs": 268
  },
  {
    "company_name": "SpaceXAI",
    "board_token": "xai",
    "fresh_jobs": 252
  },
  {
    "company_name": "Scout Motors",
    "board_token": "scoutmotors",
    "fresh_jobs": 248
  },
  {
    "company_name": "Wolt - English",
    "board_token": "wolt",
    "fresh_jobs": 247
  },
  {
    "company_name": "Curaleaf",
    "board_token": "curaleaf",
    "fresh_jobs": 246
  },
  {
    "company_name": "Green Thumb",
    "board_token": "greenthumbindustries",
    "fresh_jobs": 244
  },
  {
    "company_name": "ACCEL Schools",
    "board_token": "accelschools",
    "fresh_jobs": 240
  },
  {
    "company_name": "AlphaSense",
    "board_token": "alphasense",
    "fresh_jobs": 235
  },
  {
    "company_name": "Guidepost Montessori",
    "board_token": "guidepostmontessori",
    "fresh_jobs": 231
  },
  {
    "company_name": "Marksman Security LLC",
    "board_token": "marksman",
    "fresh_jobs": 230
  },
  {
    "company_name": "SharkNinja",
    "board_token": "sharkninjaoperatingllc",
    "fresh_jobs": 229
  },
  {
    "company_name": "Veeam Software",
    "board_token": "veeamsoftware",
    "fresh_jobs": 228
  },
  {
    "company_name": "AST SpaceMobile",
    "board_token": "astspacemobile",
    "fresh_jobs": 227
  },
  {
    "company_name": "DEPT®",
    "board_token": "dept",
    "fresh_jobs": 226
  },
  {
    "company_name": "SentinelOne",
    "board_token": "sentinellabs",
    "fresh_jobs": 226
  },
  {
    "company_name": "Compass",
    "board_token": "urbancompass",
    "fresh_jobs": 212
  },
  {
    "company_name": "GRVTY",
    "board_token": "grvty",
    "fresh_jobs": 211
  },
  {
    "company_name": "Spektrum",
    "board_token": "spektrum",
    "fresh_jobs": 207
  },
  {
    "company_name": "iCapital",
    "board_token": "icapitalnetwork",
    "fresh_jobs": 206
  },
  {
    "company_name": "JD Sports",
    "board_token": "jdsports",
    "fresh_jobs": 206
  },
  {
    "company_name": "Ennoble Care",
    "board_token": "ennoblecare",
    "fresh_jobs": 203
  },
  {
    "company_name": "PlayStation Global",
    "board_token": "sonyinteractiveentertainmentglobal",
    "fresh_jobs": 200
  },
  {
    "company_name": "ALTEN Technology USA",
    "board_token": "altentechnologyusa",
    "fresh_jobs": 197
  },
  {
    "company_name": "Eliot Community Human Services",
    "board_token": "eliotcommunityhumanservices",
    "fresh_jobs": 197
  },
  {
    "company_name": "The Specialty Alliance",
    "board_token": "thegialliancemanagementllccompany",
    "fresh_jobs": 196
  },
  {
    "company_name": "Encora",
    "board_token": "encora10",
    "fresh_jobs": 193
  },
  {
    "company_name": "XP Inc.",
    "board_token": "xpinc",
    "fresh_jobs": 193
  },
  {
    "company_name": "The Trade Desk",
    "board_token": "thetradedesk",
    "fresh_jobs": 189
  },
  {
    "company_name": "AEG Worldwide",
    "board_token": "aegworldwide",
    "fresh_jobs": 187
  },
  {
    "company_name": "NICE",
    "board_token": "nice",
    "fresh_jobs": 187
  },
  {
    "company_name": "Sezzle",
    "board_token": "sezzle",
    "fresh_jobs": 186
  },
  {
    "company_name": "WPP",
    "board_token": "wpp",
    "fresh_jobs": 186
  },
  {
    "company_name": "Apex Companies",
    "board_token": "apexcompanies",
    "fresh_jobs": 185
  },
  {
    "company_name": "Oldcastle BuildingEnvelope",
    "board_token": "oldcastlebuildingenvelope",
    "fresh_jobs": 185
  },
  {
    "company_name": "Axiom Talent Platform",
    "board_token": "axiomtalentplatform",
    "fresh_jobs": 182
  },
  {
    "company_name": "True Anomaly",
    "board_token": "trueanomalyinc",
    "fresh_jobs": 181
  },
  {
    "company_name": "Atwell, LLC",
    "board_token": "atwellgroup",
    "fresh_jobs": 180
  },
  {
    "company_name": "Datavant",
    "board_token": "datavant2",
    "fresh_jobs": 179
  },
  {
    "company_name": "Lakefield Veterinary Group",
    "board_token": "lakefieldveterinarygroup",
    "fresh_jobs": 179
  },
  {
    "company_name": "Ebury",
    "board_token": "ebury",
    "fresh_jobs": 177
  },
  {
    "company_name": "Joya",
    "board_token": "joya",
    "fresh_jobs": 177
  },
  {
    "company_name": "Otterbein SeniorLife",
    "board_token": "otterbein",
    "fresh_jobs": 175
  },
  {
    "company_name": "C6 Bank",
    "board_token": "c6bank",
    "fresh_jobs": 172
  },
  {
    "company_name": "Ubiquiti",
    "board_token": "ubiquiti",
    "fresh_jobs": 171
  },
  {
    "company_name": "Burson",
    "board_token": "bursonglobalcareers",
    "fresh_jobs": 169
  },
  {
    "company_name": "Precision Medicine Group",
    "board_token": "precisionmedicinegroup",
    "fresh_jobs": 169
  },
  {
    "company_name": "Vast",
    "board_token": "vast",
    "fresh_jobs": 169
  },
  {
    "company_name": "Xometry",
    "board_token": "xometry",
    "fresh_jobs": 169
  },
  {
    "company_name": "Appian Corporation",
    "board_token": "appian",
    "fresh_jobs": 168
  },
  {
    "company_name": "Plata Card",
    "board_token": "platacard",
    "fresh_jobs": 165
  },
  {
    "company_name": "Hasbro",
    "board_token": "hasbro",
    "fresh_jobs": 164
  },
  {
    "company_name": "Wilson Elser - Attorneys",
    "board_token": "wilsonelserattorneys",
    "fresh_jobs": 164
  },
  {
    "company_name": "Agibank",
    "board_token": "agibank",
    "fresh_jobs": 163
  },
  {
    "company_name": "gorjana",
    "board_token": "gorjana",
    "fresh_jobs": 163
  },
  {
    "company_name": "Astera Labs",
    "board_token": "asteralabs",
    "fresh_jobs": 162
  },
  {
    "company_name": "Archer",
    "board_token": "archer56",
    "fresh_jobs": 161
  },
  {
    "company_name": "Suitsupply",
    "board_token": "suitsupply",
    "fresh_jobs": 161
  },
  {
    "company_name": "CookUnity",
    "board_token": "cookunity",
    "fresh_jobs": 157
  },
  {
    "company_name": "TooJay’s Deli • Bakery • Restaurant",
    "board_token": "toojaysdeli",
    "fresh_jobs": 156
  },
  {
    "company_name": "DLR Group",
    "board_token": "dlrgroup",
    "fresh_jobs": 152
  },
  {
    "company_name": "Fanatics Collectibles",
    "board_token": "fanaticscollectibles",
    "fresh_jobs": 152
  },
  {
    "company_name": "Wellthy Care Network",
    "board_token": "wellthy-care-network",
    "fresh_jobs": 151
  },
  {
    "company_name": "Pearce Services",
    "board_token": "pearceservices",
    "fresh_jobs": 150
  },
  {
    "company_name": "Voyager Technologies, Inc.",
    "board_token": "voyagertechnologiesinc",
    "fresh_jobs": 150
  },
  {
    "company_name": "Sony Music Global Job Board",
    "board_token": "sonymusicentertainment",
    "fresh_jobs": 149
  },
  {
    "company_name": "Anaplan",
    "board_token": "anaplan",
    "fresh_jobs": 146
  },
  {
    "company_name": "Quince",
    "board_token": "quince",
    "fresh_jobs": 145
  },
  {
    "company_name": "DigitalOcean",
    "board_token": "digitalocean98",
    "fresh_jobs": 143
  },
  {
    "company_name": "Helsing",
    "board_token": "helsing",
    "fresh_jobs": 143
  },
  {
    "company_name": "Kestra Medical Technologies Inc.",
    "board_token": "kestramedicaltechnologiesinc",
    "fresh_jobs": 143
  },
  {
    "company_name": "Zeta Global",
    "board_token": "zetaglobal",
    "fresh_jobs": 143
  },
  {
    "company_name": "STR",
    "board_token": "systemstechnologyresearch",
    "fresh_jobs": 142
  },
  {
    "company_name": "Workato",
    "board_token": "workato",
    "fresh_jobs": 142
  },
  {
    "company_name": "CHAOS Industries",
    "board_token": "chaosindustries",
    "fresh_jobs": 141
  },
  {
    "company_name": "Gotion, Inc.",
    "board_token": "gotion",
    "fresh_jobs": 140
  },
  {
    "company_name": "Helping Hands Family",
    "board_token": "helpinghandsfamily",
    "fresh_jobs": 139
  },
  {
    "company_name": "Netskope",
    "board_token": "netskope",
    "fresh_jobs": 139
  },
  {
    "company_name": "Nox Group",
    "board_token": "noxgroup",
    "fresh_jobs": 139
  },
  {
    "company_name": "Human Agency",
    "board_token": "humanagency",
    "fresh_jobs": 137
  },
  {
    "company_name": "Jensen Hughes",
    "board_token": "jensenhughes",
    "fresh_jobs": 137
  },
  {
    "company_name": "Lush Handmade Cosmetics",
    "board_token": "lush",
    "fresh_jobs": 137
  },
  {
    "company_name": "Mejuri",
    "board_token": "mejuri",
    "fresh_jobs": 137
  },
  {
    "company_name": "Careers at KKR",
    "board_token": "stage",
    "fresh_jobs": 136
  },
  {
    "company_name": "EOS",
    "board_token": "eositsolutions",
    "fresh_jobs": 136
  },
  {
    "company_name": "Valtech",
    "board_token": "valtech",
    "fresh_jobs": 136
  },
  {
    "company_name": "Apartment Life",
    "board_token": "apartmentlife",
    "fresh_jobs": 135
  },
  {
    "company_name": "CannonDesign",
    "board_token": "cannondesign",
    "fresh_jobs": 135
  },
  {
    "company_name": "Five9",
    "board_token": "five9",
    "fresh_jobs": 133
  },
  {
    "company_name": "InHome Therapy",
    "board_token": "inhometherapy",
    "fresh_jobs": 133
  },
  {
    "company_name": "Ogilvy",
    "board_token": "ogilvy",
    "fresh_jobs": 133
  },
  {
    "company_name": "Precision for Medicine",
    "board_token": "pfm",
    "fresh_jobs": 133
  },
  {
    "company_name": "Theoria Medical",
    "board_token": "theoriamedical",
    "fresh_jobs": 133
  },
  {
    "company_name": "VetEvolve",
    "board_token": "vetevolve",
    "fresh_jobs": 133
  },
  {
    "company_name": "Reformation",
    "board_token": "reformation",
    "fresh_jobs": 132
  },
  {
    "company_name": "Snap! Mobile, Inc.",
    "board_token": "snapmobileinc",
    "fresh_jobs": 132
  },
  {
    "company_name": "InterSystems",
    "board_token": "intersystems",
    "fresh_jobs": 131
  },
  {
    "company_name": "Moniepoint",
    "board_token": "moniepoint",
    "fresh_jobs": 131
  },
  {
    "company_name": "WelbeHealth",
    "board_token": "welbehealth",
    "fresh_jobs": 131
  },
  {
    "company_name": "VML/WPP Enterprise Solutions",
    "board_token": "vmlenterprisesolutions",
    "fresh_jobs": 130
  },
  {
    "company_name": "Wayve",
    "board_token": "wayve",
    "fresh_jobs": 130
  },
  {
    "company_name": "Family of Kidz",
    "board_token": "familyofkidz",
    "fresh_jobs": 128
  },
  {
    "company_name": "Via",
    "board_token": "via",
    "fresh_jobs": 128
  },
  {
    "company_name": "Re:Build Manufacturing",
    "board_token": "rebuildmanufacturing",
    "fresh_jobs": 126
  },
  {
    "company_name": "Artefact",
    "board_token": "artefact",
    "fresh_jobs": 125
  },
  {
    "company_name": "Barbaricum",
    "board_token": "barbaricum",
    "fresh_jobs": 125
  },
  {
    "company_name": "Doctolib",
    "board_token": "doctolib",
    "fresh_jobs": 125
  },
  {
    "company_name": "The Copper River Family of Companies",
    "board_token": "crfamilyofcompanies",
    "fresh_jobs": 125
  },
  {
    "company_name": "Walden Security",
    "board_token": "waldensecurity",
    "fresh_jobs": 125
  },
  {
    "company_name": "Vail Health Hospital",
    "board_token": "vailclinicincdbavailhealthhospital",
    "fresh_jobs": 124
  },
  {
    "company_name": "Addepar",
    "board_token": "addepar1",
    "fresh_jobs": 123
  },
  {
    "company_name": "Guidepoint",
    "board_token": "guidepoint",
    "fresh_jobs": 122
  },
  {
    "company_name": "Fin",
    "board_token": "intercom",
    "fresh_jobs": 120
  },
  {
    "company_name": "LG Electronics",
    "board_token": "lgelectronics",
    "fresh_jobs": 120
  },
  {
    "company_name": "Bethesda Health Group",
    "board_token": "bethesdahealthgroup",
    "fresh_jobs": 119
  },
  {
    "company_name": "Cortica - Neurodevelopmental",
    "board_token": "allcareers",
    "fresh_jobs": 119
  },
  {
    "company_name": "Clara",
    "board_token": "clara",
    "fresh_jobs": 118
  },
  {
    "company_name": "Freedom Technology Solutions Group",
    "board_token": "freedomconsulting",
    "fresh_jobs": 118
  },
  {
    "company_name": "Payoneer",
    "board_token": "payoneer",
    "fresh_jobs": 118
  },
  {
    "company_name": "Proof",
    "board_token": "proof",
    "fresh_jobs": 118
  },
  {
    "company_name": "2K",
    "board_token": "2k",
    "fresh_jobs": 117
  },
  {
    "company_name": "ABC Legal Services",
    "board_token": "abclegalservices",
    "fresh_jobs": 116
  },
  {
    "company_name": "Buckner International",
    "board_token": "bucknerinternational",
    "fresh_jobs": 116
  },
  {
    "company_name": "Betsson Group",
    "board_token": "betsson",
    "fresh_jobs": 115
  },
  {
    "company_name": "General Matter",
    "board_token": "generalmatter",
    "fresh_jobs": 115
  },
  {
    "company_name": "GLG",
    "board_token": "gersonlehrmangroup",
    "fresh_jobs": 115
  },
  {
    "company_name": "K2 Space",
    "board_token": "k2spacecorporation",
    "fresh_jobs": 115
  },
  {
    "company_name": "Compass Pathways",
    "board_token": "compasspathways",
    "fresh_jobs": 114
  },
  {
    "company_name": "Fairstead ESC LLC",
    "board_token": "fairsteadescllc",
    "fresh_jobs": 114
  },
  {
    "company_name": "Diligent Corporation",
    "board_token": "diligentcorporation",
    "fresh_jobs": 113
  },
  {
    "company_name": "EPIC Brokers",
    "board_token": "edgewoodpartnersinsurancecenter",
    "fresh_jobs": 113
  },
  {
    "company_name": "Acorn Health",
    "board_token": "acornhealth",
    "fresh_jobs": 112
  },
  {
    "company_name": "Lila Sciences",
    "board_token": "lilasciences",
    "fresh_jobs": 112
  },
  {
    "company_name": "Svetness Personal Training",
    "board_token": "svetness",
    "fresh_jobs": 112
  },
  {
    "company_name": "Woolpert",
    "board_token": "woolpert",
    "fresh_jobs": 112
  },
  {
    "company_name": "Van Leeuwen Ice Cream",
    "board_token": "vanleeuwenicecream",
    "fresh_jobs": 111
  },
  {
    "company_name": "Allen Integrated Solutions",
    "board_token": "allenintegratedsolutions",
    "fresh_jobs": 110
  },
  {
    "company_name": "Careers at Eucalyptus",
    "board_token": "eucalyptus",
    "fresh_jobs": 110
  },
  {
    "company_name": "Industrial Electric Manufacturing",
    "board_token": "industrialelectricmanufacturing",
    "fresh_jobs": 110
  },
  {
    "company_name": "Specialty1 Partners",
    "board_token": "specialty1",
    "fresh_jobs": 110
  },
  {
    "company_name": "The Quality Group GmbH",
    "board_token": "thequalitygroupgmbh1",
    "fresh_jobs": 109
  },
  {
    "company_name": "IXL Learning",
    "board_token": "ixllearning",
    "fresh_jobs": 107
  },
  {
    "company_name": "Triumvirate Environmental",
    "board_token": "triumvirateenvironmental",
    "fresh_jobs": 107
  },
  {
    "company_name": "Lincoln Property Company",
    "board_token": "lpc",
    "fresh_jobs": 106
  },
  {
    "company_name": "Townsquare Media",
    "board_token": "townsquaremedia",
    "fresh_jobs": 105
  },
  {
    "company_name": "Muon Space",
    "board_token": "muonspace",
    "fresh_jobs": 104
  },
  {
    "company_name": "Dexis",
    "board_token": "dexisconsultinggroup",
    "fresh_jobs": 103
  },
  {
    "company_name": "Eating Recovery Center",
    "board_token": "erc8585757pathlight53t353",
    "fresh_jobs": 102
  },
  {
    "company_name": "Isar Aerospace SE",
    "board_token": "isaraerospace",
    "fresh_jobs": 102
  },
  {
    "company_name": "United Vein & Vascular Centers",
    "board_token": "unitedveincenters",
    "fresh_jobs": 102
  },
  {
    "company_name": "Hawthorne Residential Partners",
    "board_token": "hrpliving",
    "fresh_jobs": 101
  },
  {
    "company_name": "Ōura",
    "board_token": "oura",
    "fresh_jobs": 101
  },
  {
    "company_name": "Success Academy Charter Schools",
    "board_token": "successacademycharterschool",
    "fresh_jobs": 101
  },
  {
    "company_name": "Advanced Technology Services",
    "board_token": "advancedtechnologyservices",
    "fresh_jobs": 100
  },
  {
    "company_name": "Bond Vet",
    "board_token": "bondvet",
    "fresh_jobs": 100
  },
  {
    "company_name": "Upstart",
    "board_token": "upstart",
    "fresh_jobs": 100
  },
  {
    "company_name": "Cottingham & Butler",
    "board_token": "cottinghambutlerinsuranceservicesinc",
    "fresh_jobs": 99
  },
  {
    "company_name": "Flagship Pioneering, Inc.",
    "board_token": "flagshippioneeringinc",
    "fresh_jobs": 99
  },
  {
    "company_name": "J&J Snack Foods",
    "board_token": "jjsnackfoods",
    "fresh_jobs": 99
  },
  {
    "company_name": "Shields Health Solutions",
    "board_token": "shieldshealthsolutions",
    "fresh_jobs": 99
  },
  {
    "company_name": "SPS North America",
    "board_token": "spsnorthamerica",
    "fresh_jobs": 99
  },
  {
    "company_name": "Ursa Major",
    "board_token": "ursamajor",
    "fresh_jobs": 99
  },
  {
    "company_name": "Capgemini Invent",
    "board_token": "capgeminideutschlandgmbh",
    "fresh_jobs": 98
  },
  {
    "company_name": "Titan Security Group",
    "board_token": "tsg",
    "fresh_jobs": 98
  },
  {
    "company_name": "Veritas Veterinary Partners",
    "board_token": "veritasvetpartners",
    "fresh_jobs": 96
  },
  {
    "company_name": "North Point Technology",
    "board_token": "northpointtechnology",
    "fresh_jobs": 95
  },
  {
    "company_name": "Skilled Wound Care",
    "board_token": "skilledwoundcare",
    "fresh_jobs": 95
  },
  {
    "company_name": "The Quality Group",
    "board_token": "thequalitygroupgmbh2",
    "fresh_jobs": 95
  },
  {
    "company_name": "VSC Fire & Security",
    "board_token": "vscfiresecurityinc",
    "fresh_jobs": 95
  },
  {
    "company_name": "Fundraise Up",
    "board_token": "fundraiseup",
    "fresh_jobs": 94
  },
  {
    "company_name": "Omnicom Media",
    "board_token": "mediabrands",
    "fresh_jobs": 94
  },
  {
    "company_name": "Arco Educação",
    "board_token": "arcoeducacao",
    "fresh_jobs": 93
  },
  {
    "company_name": "IVX Health",
    "board_token": "ivxhealth",
    "fresh_jobs": 93
  },
  {
    "company_name": "Mercer Advisors",
    "board_token": "merceradvisors",
    "fresh_jobs": 93
  },
  {
    "company_name": "Smartsheet",
    "board_token": "smartsheet",
    "fresh_jobs": 93
  },
  {
    "company_name": "Benesch",
    "board_token": "alfredbeneschco",
    "fresh_jobs": 92
  },
  {
    "company_name": "Avanath",
    "board_token": "communitymanager",
    "fresh_jobs": 91
  },
  {
    "company_name": "Fictiv",
    "board_token": "fictiv",
    "fresh_jobs": 91
  },
  {
    "company_name": "McClure Oil Corporation",
    "board_token": "mcclureoilcorporation",
    "fresh_jobs": 91
  },
  {
    "company_name": "OpenTable",
    "board_token": "opentable",
    "fresh_jobs": 91
  },
  {
    "company_name": "POWERX",
    "board_token": "powerx",
    "fresh_jobs": 91
  },
  {
    "company_name": "Simtra BioPharma Solutions",
    "board_token": "simtrabps",
    "fresh_jobs": 91
  },
  {
    "company_name": "Sono Bello",
    "board_token": "sonobello",
    "fresh_jobs": 91
  },
  {
    "company_name": "Cato Networks",
    "board_token": "catonetworks",
    "fresh_jobs": 90
  },
  {
    "company_name": "MrBeast",
    "board_token": "mrbeastyoutube",
    "fresh_jobs": 90
  },
  {
    "company_name": "Presidents Summit",
    "board_token": "presidentssummit",
    "fresh_jobs": 90
  },
  {
    "company_name": "Guild Garage Group",
    "board_token": "guildgaragegroup",
    "fresh_jobs": 89
  },
  {
    "company_name": "MetroStar",
    "board_token": "metrostarsystems",
    "fresh_jobs": 89
  },
  {
    "company_name": "BridgeBio Pharma",
    "board_token": "bridgebio",
    "fresh_jobs": 88
  },
  {
    "company_name": "Decima International",
    "board_token": "decimainternational",
    "fresh_jobs": 88
  },
  {
    "company_name": "US Conec, Ltd.",
    "board_token": "usconec",
    "fresh_jobs": 88
  },
  {
    "company_name": "Azurity Pharmaceuticals - US",
    "board_token": "azuritypharmaceuticals",
    "fresh_jobs": 87
  },
  {
    "company_name": "Corcept Therapeutics",
    "board_token": "corcepttherapeutics",
    "fresh_jobs": 87
  },
  {
    "company_name": "Diana Health",
    "board_token": "dianahealth94",
    "fresh_jobs": 87
  },
  {
    "company_name": "DoiT",
    "board_token": "doitintl",
    "fresh_jobs": 87
  },
  {
    "company_name": "GenScript/ProBio",
    "board_token": "genscript",
    "fresh_jobs": 87
  },
  {
    "company_name": "StackAdapt",
    "board_token": "stackadapt",
    "fresh_jobs": 87
  },
  {
    "company_name": "Axsome Therapeutics",
    "board_token": "axsometherapeutics",
    "fresh_jobs": 86
  },
  {
    "company_name": "Blackbird Health",
    "board_token": "blackbirdhealth",
    "fresh_jobs": 86
  },
  {
    "company_name": "Exadel",
    "board_token": "externaljobboards",
    "fresh_jobs": 86
  },
  {
    "company_name": "Glean",
    "board_token": "gleanwork",
    "fresh_jobs": 86
  },
  {
    "company_name": "HP Hood",
    "board_token": "hoodhp",
    "fresh_jobs": 86
  },
  {
    "company_name": "Alarm.com",
    "board_token": "alarmcom",
    "fresh_jobs": 85
  },
  {
    "company_name": "Highwire",
    "board_token": "highwire",
    "fresh_jobs": 85
  },
  {
    "company_name": "PayPay",
    "board_token": "paypay",
    "fresh_jobs": 85
  },
  {
    "company_name": "SOL Mental Health",
    "board_token": "solmentalhealth",
    "fresh_jobs": 85
  },
  {
    "company_name": "Dialpad",
    "board_token": "dialpad",
    "fresh_jobs": 84
  },
  {
    "company_name": "Madison Reed",
    "board_token": "madisonreedcolorbar",
    "fresh_jobs": 84
  },
  {
    "company_name": "Peregrine Technologies",
    "board_token": "peregrinetechnologies",
    "fresh_jobs": 84
  },
  {
    "company_name": "Taboola",
    "board_token": "taboola",
    "fresh_jobs": 84
  },
  {
    "company_name": "Elite Dental Partners",
    "board_token": "elitedentalpartnersllc",
    "fresh_jobs": 83
  },
  {
    "company_name": "Philz Coffee",
    "board_token": "philzcoffeecareers",
    "fresh_jobs": 83
  },
  {
    "company_name": "AlphaSights",
    "board_token": "alphasights",
    "fresh_jobs": 82
  },
  {
    "company_name": "Analytic Services Inc",
    "board_token": "analyticservicesinc",
    "fresh_jobs": 82
  },
  {
    "company_name": "Ardent",
    "board_token": "ardentmc",
    "fresh_jobs": 82
  },
  {
    "company_name": "BillionToOne",
    "board_token": "billiontoone",
    "fresh_jobs": 82
  },
  {
    "company_name": "Careers at Tide",
    "board_token": "tide",
    "fresh_jobs": 82
  },
  {
    "company_name": "Dental365",
    "board_token": "dental365",
    "fresh_jobs": 82
  },
  {
    "company_name": "OneTrust",
    "board_token": "onetrust",
    "fresh_jobs": 82
  },
  {
    "company_name": "OPSWAT",
    "board_token": "opswat",
    "fresh_jobs": 82
  },
  {
    "company_name": "Tecovas",
    "board_token": "tecovas",
    "fresh_jobs": 82
  },
  {
    "company_name": "Valar Atomics",
    "board_token": "valaratomics",
    "fresh_jobs": 82
  },
  {
    "company_name": "Apptronik",
    "board_token": "apptronik",
    "fresh_jobs": 81
  },
  {
    "company_name": "Brilliant Earth",
    "board_token": "brilliantearth",
    "fresh_jobs": 81
  },
  {
    "company_name": "Garner Health",
    "board_token": "garnerhealth",
    "fresh_jobs": 81
  },
  {
    "company_name": "Harness",
    "board_token": "harnessinc",
    "fresh_jobs": 81
  },
  {
    "company_name": "Blank Street",
    "board_token": "blankstreet",
    "fresh_jobs": 80
  },
  {
    "company_name": "Hightouch",
    "board_token": "hightouch",
    "fresh_jobs": 80
  },
  {
    "company_name": "Crestwood Behavioral Health",
    "board_token": "crestwoodcareers",
    "fresh_jobs": 79
  },
  {
    "company_name": "iFood",
    "board_token": "ifoodcarreiras",
    "fresh_jobs": 79
  },
  {
    "company_name": "takealot.com",
    "board_token": "takealotcom",
    "fresh_jobs": 79
  },
  {
    "company_name": "The Nuclear Company",
    "board_token": "thenuclearcompany",
    "fresh_jobs": 79
  },
  {
    "company_name": "At Home Healthcare",
    "board_token": "athomehealth",
    "fresh_jobs": 78
  },
  {
    "company_name": "Inversion",
    "board_token": "inversionspace",
    "fresh_jobs": 78
  },
  {
    "company_name": "Myriad360",
    "board_token": "myriad360",
    "fresh_jobs": 78
  },
  {
    "company_name": "Teads",
    "board_token": "teads1",
    "fresh_jobs": 78
  },
  {
    "company_name": "AirTrunk",
    "board_token": "airtrunk",
    "fresh_jobs": 77
  },
  {
    "company_name": "Cohere Health",
    "board_token": "coherehealth",
    "fresh_jobs": 77
  },
  {
    "company_name": "Inovalon",
    "board_token": "inovalon",
    "fresh_jobs": 77
  },
  {
    "company_name": "Neros Technologies",
    "board_token": "nerostechnologies",
    "fresh_jobs": 77
  },
  {
    "company_name": "Sunnyside*",
    "board_token": "sunnyside",
    "fresh_jobs": 77
  },
  {
    "company_name": "CaptiveAire",
    "board_token": "captiveaire",
    "fresh_jobs": 76
  },
  {
    "company_name": "Clearway Energy",
    "board_token": "clearwayjobs",
    "fresh_jobs": 76
  },
  {
    "company_name": "Cresco Labs",
    "board_token": "crescolabs",
    "fresh_jobs": 76
  },
  {
    "company_name": "Fanatics Betting & Gaming",
    "board_token": "fanaticsfbg",
    "fresh_jobs": 76
  },
  {
    "company_name": "Harbinger Motors Inc.",
    "board_token": "harbingermotors",
    "fresh_jobs": 76
  },
  {
    "company_name": "National Life Insurance Company",
    "board_token": "nationallifeinsurancecompany",
    "fresh_jobs": 76
  },
  {
    "company_name": "Orion Innovation",
    "board_token": "orioninnovation",
    "fresh_jobs": 76
  },
  {
    "company_name": "Poland and Middle-Eastern Europe",
    "board_token": "xebiacee",
    "fresh_jobs": 76
  },
  {
    "company_name": "VaynerMedia LLC",
    "board_token": "vaynermedia",
    "fresh_jobs": 76
  },
  {
    "company_name": "Zone 5 Technologies",
    "board_token": "zone5technologies",
    "fresh_jobs": 76
  },
  {
    "company_name": "Aviation Institute of Maintenance",
    "board_token": "aviationinstituteofmaintenance",
    "fresh_jobs": 75
  },
  {
    "company_name": "Captivation Software",
    "board_token": "captivation",
    "fresh_jobs": 75
  },
  {
    "company_name": "Chowbus",
    "board_token": "chowbus",
    "fresh_jobs": 75
  },
  {
    "company_name": "Crisp Recruit",
    "board_token": "crisprecruit",
    "fresh_jobs": 75
  },
  {
    "company_name": "Giga Energy",
    "board_token": "gigaenergy",
    "fresh_jobs": 75
  },
  {
    "company_name": "IMA Financial Group",
    "board_token": "imafinancialgroup",
    "fresh_jobs": 75
  },
  {
    "company_name": "JetBrains",
    "board_token": "jetbrains",
    "fresh_jobs": 75
  },
  {
    "company_name": "Neuralink",
    "board_token": "neuralink",
    "fresh_jobs": 75
  },
  {
    "company_name": "Nourish",
    "board_token": "usenourish",
    "fresh_jobs": 75
  },
  {
    "company_name": "Tulip Interfaces",
    "board_token": "tulip",
    "fresh_jobs": 75
  },
  {
    "company_name": "Ascend Partner Firms",
    "board_token": "ascendtogether",
    "fresh_jobs": 74
  },
  {
    "company_name": "Freeform",
    "board_token": "freeformfuturecorp",
    "fresh_jobs": 74
  },
  {
    "company_name": "McAdams",
    "board_token": "mcadams",
    "fresh_jobs": 74
  },
  {
    "company_name": "PubMatic",
    "board_token": "pubmatic",
    "fresh_jobs": 74
  },
  {
    "company_name": "Weight Watchers",
    "board_token": "ww",
    "fresh_jobs": 74
  },
  {
    "company_name": "Headlands Research",
    "board_token": "headlandsresearch",
    "fresh_jobs": 73
  },
  {
    "company_name": "LA28 (Web)",
    "board_token": "la28careers",
    "fresh_jobs": 73
  },
  {
    "company_name": "Launch Potato",
    "board_token": "launch2",
    "fresh_jobs": 73
  },
  {
    "company_name": "Legend Biotech US",
    "board_token": "legendcareers",
    "fresh_jobs": 73
  },
  {
    "company_name": "Metropolis",
    "board_token": "metropolis",
    "fresh_jobs": 73
  },
  {
    "company_name": "NeuraFlash, Part of Accenture",
    "board_token": "neuraflash",
    "fresh_jobs": 73
  },
  {
    "company_name": "Proton",
    "board_token": "proton",
    "fresh_jobs": 73
  },
  {
    "company_name": "Tyson & Mendes LLP",
    "board_token": "tysonmendesllp",
    "fresh_jobs": 73
  },
  {
    "company_name": "Dyne Therapeutics",
    "board_token": "dynetherapeutics",
    "fresh_jobs": 72
  },
  {
    "company_name": "GFiber",
    "board_token": "googlefiber",
    "fresh_jobs": 72
  },
  {
    "company_name": "LotusWorks",
    "board_token": "lotusworks",
    "fresh_jobs": 72
  },
  {
    "company_name": "Tailscale",
    "board_token": "tailscale",
    "fresh_jobs": 72
  },
  {
    "company_name": "BGE, Inc",
    "board_token": "bgeinc",
    "fresh_jobs": 71
  },
  {
    "company_name": "impact.com",
    "board_token": "impact",
    "fresh_jobs": 71
  },
  {
    "company_name": "Kodiak",
    "board_token": "kodiak",
    "fresh_jobs": 71
  },
  {
    "company_name": "RTB House",
    "board_token": "rtbhouse",
    "fresh_jobs": 71
  },
  {
    "company_name": "Smartly",
    "board_token": "smartlyio",
    "fresh_jobs": 71
  },
  {
    "company_name": "Starling Oncology",
    "board_token": "theoncologyinstitute",
    "fresh_jobs": 71
  },
  {
    "company_name": "Summit Therapeutics",
    "board_token": "summittherapeutics",
    "fresh_jobs": 71
  },
  {
    "company_name": "Alpaca",
    "board_token": "alpaca",
    "fresh_jobs": 70
  },
  {
    "company_name": "Divergent",
    "board_token": "divergent",
    "fresh_jobs": 70
  },
  {
    "company_name": "Engine",
    "board_token": "engine",
    "fresh_jobs": 70
  },
  {
    "company_name": "KnowBe4",
    "board_token": "knowbe4",
    "fresh_jobs": 70
  },
  {
    "company_name": "Ping Identity",
    "board_token": "pingidentity",
    "fresh_jobs": 70
  },
  {
    "company_name": "Real Chemistry",
    "board_token": "realchemistry",
    "fresh_jobs": 70
  },
  {
    "company_name": "Wrike",
    "board_token": "wrike",
    "fresh_jobs": 70
  },
  {
    "company_name": "Charles River Associates",
    "board_token": "charlesriverassociates",
    "fresh_jobs": 69
  },
  {
    "company_name": "Commvault",
    "board_token": "commvault",
    "fresh_jobs": 69
  },
  {
    "company_name": "Construction Resources",
    "board_token": "constructionresources",
    "fresh_jobs": 69
  },
  {
    "company_name": "New Era Technology",
    "board_token": "neweratech",
    "fresh_jobs": 69
  },
  {
    "company_name": "PMG",
    "board_token": "pmg",
    "fresh_jobs": 69
  },
  {
    "company_name": "Vaco LLC",
    "board_token": "vaco",
    "fresh_jobs": 69
  },
  {
    "company_name": "Wave",
    "board_token": "wavemm1",
    "fresh_jobs": 69
  },
  {
    "company_name": "aCommerce",
    "board_token": "acommerce",
    "fresh_jobs": 68
  },
  {
    "company_name": "mthree Recruiting Portal",
    "board_token": "mthreerecruitingportal",
    "fresh_jobs": 68
  },
  {
    "company_name": "Appier",
    "board_token": "appier",
    "fresh_jobs": 67
  },
  {
    "company_name": "Blink Health",
    "board_token": "blinkhealth",
    "fresh_jobs": 67
  },
  {
    "company_name": "CoreWeave Europe",
    "board_token": "coreweaveu",
    "fresh_jobs": 67
  },
  {
    "company_name": "DigiCert",
    "board_token": "digicert",
    "fresh_jobs": 67
  },
  {
    "company_name": "Effective School Solutions",
    "board_token": "effectiveschoolsolutions",
    "fresh_jobs": 67
  },
  {
    "company_name": "KRAFTON",
    "board_token": "krafton",
    "fresh_jobs": 67
  },
  {
    "company_name": "Luminary Hospice",
    "board_token": "luminaryhospice",
    "fresh_jobs": 67
  },
  {
    "company_name": "Misfits Market",
    "board_token": "misfitsmarket",
    "fresh_jobs": 67
  },
  {
    "company_name": "Modern Animal",
    "board_token": "modernanimal",
    "fresh_jobs": 67
  },
  {
    "company_name": "Pediatrics Plus Website",
    "board_token": "pediatricsplus",
    "fresh_jobs": 67
  },
  {
    "company_name": "Rockstar Games",
    "board_token": "rockstargames",
    "fresh_jobs": 67
  },
  {
    "company_name": "Saxbys",
    "board_token": "saxbys",
    "fresh_jobs": 67
  },
  {
    "company_name": "Too Good To Go",
    "board_token": "toogoodtogo",
    "fresh_jobs": 67
  },
  {
    "company_name": "Wilson Elser - Business & Legal Professionals",
    "board_token": "wilsonelser",
    "fresh_jobs": 67
  },
  {
    "company_name": "Agility Robotics",
    "board_token": "agilityrobotics",
    "fresh_jobs": 66
  },
  {
    "company_name": "Aspire Health and Community Services",
    "board_token": "aspirehealthalliance",
    "fresh_jobs": 66
  },
  {
    "company_name": "BeyondTrust",
    "board_token": "beyondtrust",
    "fresh_jobs": 66
  },
  {
    "company_name": "C3 AI",
    "board_token": "c3iot",
    "fresh_jobs": 66
  },
  {
    "company_name": "Caylent",
    "board_token": "caylent",
    "fresh_jobs": 66
  },
  {
    "company_name": "Kaseya Careers",
    "board_token": "kaseya",
    "fresh_jobs": 66
  },
  {
    "company_name": "Mood Health",
    "board_token": "moodhealth",
    "fresh_jobs": 66
  },
  {
    "company_name": "Naked Farmer Careers",
    "board_token": "nakedfarmer",
    "fresh_jobs": 66
  },
  {
    "company_name": "QuEra Computing, Inc.",
    "board_token": "queracomputinginc",
    "fresh_jobs": 66
  },
  {
    "company_name": "ShipBob, Inc.",
    "board_token": "shipbobinc",
    "fresh_jobs": 66
  },
  {
    "company_name": "Spring Health",
    "board_token": "springhealth66",
    "fresh_jobs": 66
  },
  {
    "company_name": "StepStone Group",
    "board_token": "stepstone",
    "fresh_jobs": 66
  },
  {
    "company_name": "Think Academy US",
    "board_token": "thinkacademyus",
    "fresh_jobs": 66
  },
  {
    "company_name": "A11",
    "board_token": "projectaservicesgmbhcokg",
    "fresh_jobs": 65
  },
  {
    "company_name": "Black Duck Software, Inc.",
    "board_token": "blackduck",
    "fresh_jobs": 65
  },
  {
    "company_name": "Bloomreach",
    "board_token": "bloomreach",
    "fresh_jobs": 65
  },
  {
    "company_name": "Comstock",
    "board_token": "comstock",
    "fresh_jobs": 65
  },
  {
    "company_name": "Ensono",
    "board_token": "ensono",
    "fresh_jobs": 65
  },
  {
    "company_name": "Faraday Future",
    "board_token": "faradayfuture",
    "fresh_jobs": 65
  },
  {
    "company_name": "InMobi",
    "board_token": "inmobi",
    "fresh_jobs": 65
  },
  {
    "company_name": "OLIVER Agency - APAC",
    "board_token": "oliverseapac",
    "fresh_jobs": 65
  },
  {
    "company_name": "STUDS",
    "board_token": "studsinc",
    "fresh_jobs": 65
  },
  {
    "company_name": "Ethos Life",
    "board_token": "ethoslife",
    "fresh_jobs": 64
  },
  {
    "company_name": "GuidePoint Security",
    "board_token": "guidepointsecurity",
    "fresh_jobs": 64
  },
  {
    "company_name": "ICON",
    "board_token": "iconcareers",
    "fresh_jobs": 64
  },
  {
    "company_name": "Integrity Rehab Group",
    "board_token": "integrityrehabgroup",
    "fresh_jobs": 64
  },
  {
    "company_name": "MAP",
    "board_token": "map",
    "fresh_jobs": 64
  },
  {
    "company_name": "Trace3",
    "board_token": "trace3",
    "fresh_jobs": 64
  },
  {
    "company_name": "Two Six Technologies",
    "board_token": "twosixtechnologies",
    "fresh_jobs": 64
  },
  {
    "company_name": "Verve",
    "board_token": "verve",
    "fresh_jobs": 64
  },
  {
    "company_name": "ePlus Technology, inc.",
    "board_token": "eplusinc",
    "fresh_jobs": 63
  },
  {
    "company_name": "N2 - All Jobs",
    "board_token": "n2alljobs",
    "fresh_jobs": 63
  },
  {
    "company_name": "NexHealth",
    "board_token": "nexhealth",
    "fresh_jobs": 63
  },
  {
    "company_name": "Oklo",
    "board_token": "oklo",
    "fresh_jobs": 63
  },
  {
    "company_name": "AB InBev  | Growth Group",
    "board_token": "abinbev",
    "fresh_jobs": 62
  },
  {
    "company_name": "AppDirect",
    "board_token": "appdirect",
    "fresh_jobs": 62
  },
  {
    "company_name": "Avride",
    "board_token": "avride",
    "fresh_jobs": 62
  },
  {
    "company_name": "Boomi",
    "board_token": "boomilp",
    "fresh_jobs": 62
  },
  {
    "company_name": "Cribl",
    "board_token": "cribl",
    "fresh_jobs": 62
  },
  {
    "company_name": "dunnhumby",
    "board_token": "dunnhumby",
    "fresh_jobs": 62
  },
  {
    "company_name": "Method Co.",
    "board_token": "methodco",
    "fresh_jobs": 62
  },
  {
    "company_name": "Armada",
    "board_token": "armada",
    "fresh_jobs": 61
  },
  {
    "company_name": "Clutch Technologies Inc.",
    "board_token": "clutch",
    "fresh_jobs": 61
  },
  {
    "company_name": "Lovable",
    "board_token": "lovable",
    "fresh_jobs": 61
  },
  {
    "company_name": "Samsung Semiconductor",
    "board_token": "samsungsemiconductor",
    "fresh_jobs": 61
  },
  {
    "company_name": "Appnovation Technologies",
    "board_token": "appnovation",
    "fresh_jobs": 60
  },
  {
    "company_name": "Berkshire Group, LLC",
    "board_token": "berkshiregroupllc",
    "fresh_jobs": 60
  },
  {
    "company_name": "Career Team",
    "board_token": "careerteam",
    "fresh_jobs": 60
  },
  {
    "company_name": "Convera",
    "board_token": "convera",
    "fresh_jobs": 60
  },
  {
    "company_name": "Heartflow",
    "board_token": "heartflowinc",
    "fresh_jobs": 60
  },
  {
    "company_name": "ON.energy",
    "board_token": "onenergy",
    "fresh_jobs": 60
  },
  {
    "company_name": "Pomelo Care",
    "board_token": "pomelocare",
    "fresh_jobs": 60
  },
  {
    "company_name": "SambaNova",
    "board_token": "sambanovasystems",
    "fresh_jobs": 60
  },
  {
    "company_name": "Verra Mobility",
    "board_token": "verramobility",
    "fresh_jobs": 60
  },
  {
    "company_name": "DIG INN Restaurant Teams",
    "board_token": "digrestaurants",
    "fresh_jobs": 59
  },
  {
    "company_name": "Seneca Holdings",
    "board_token": "shinvestmentsllc",
    "fresh_jobs": 59
  },
  {
    "company_name": "AGE Solutions",
    "board_token": "agecareers",
    "fresh_jobs": 58
  },
  {
    "company_name": "Fetch",
    "board_token": "fetch",
    "fresh_jobs": 58
  },
  {
    "company_name": "First Global Management Services, Inc.",
    "board_token": "firstglobalmanagementservicesinc",
    "fresh_jobs": 58
  },
  {
    "company_name": "JRM Construction Management, LLC",
    "board_token": "jrmconstructionmanagementllc",
    "fresh_jobs": 58
  },
  {
    "company_name": "Realtor.com Careers",
    "board_token": "rdccareers",
    "fresh_jobs": 58
  },
  {
    "company_name": "Tatari",
    "board_token": "tatari",
    "fresh_jobs": 58
  },
  {
    "company_name": "The National Football League",
    "board_token": "nflcareers",
    "fresh_jobs": 58
  },
  {
    "company_name": "ClinChoice",
    "board_token": "clinchoice",
    "fresh_jobs": 57
  },
  {
    "company_name": "Compass Health Center",
    "board_token": "compasshealthcenter",
    "fresh_jobs": 57
  },
  {
    "company_name": "Exadel Inc (Website)",
    "board_token": "exadelinc",
    "fresh_jobs": 57
  },
  {
    "company_name": "Iterative Health",
    "board_token": "iterativehealth",
    "fresh_jobs": 57
  },
  {
    "company_name": "Life Skills Autism Academy",
    "board_token": "lifeskillsautismacademy",
    "fresh_jobs": 57
  },
  {
    "company_name": "Cortica",
    "board_token": "cortica",
    "fresh_jobs": 56
  },
  {
    "company_name": "Freenow by Lyft",
    "board_token": "freenow",
    "fresh_jobs": 56
  },
  {
    "company_name": "Keeper Security",
    "board_token": "keepersecurity",
    "fresh_jobs": 56
  },
  {
    "company_name": "Kyo",
    "board_token": "kyocare",
    "fresh_jobs": 56
  },
  {
    "company_name": "Podium",
    "board_token": "podium81",
    "fresh_jobs": 56
  },
  {
    "company_name": "Sony Interactive Entertainment Inc.",
    "board_token": "siei",
    "fresh_jobs": 56
  },
  {
    "company_name": "Torc Robotics",
    "board_token": "torcrobotics",
    "fresh_jobs": 56
  },
  {
    "company_name": "Wolt - Hebrew",
    "board_token": "woltisrael",
    "fresh_jobs": 56
  },
  {
    "company_name": "Core One",
    "board_token": "coreone",
    "fresh_jobs": 55
  },
  {
    "company_name": "Dark Wolf Solutions",
    "board_token": "darkwolfsolutions",
    "fresh_jobs": 55
  },
  {
    "company_name": "Defense Unicorns",
    "board_token": "defenseunicorns",
    "fresh_jobs": 55
  },
  {
    "company_name": "Foundation Risk Partners",
    "board_token": "foundationriskpartners",
    "fresh_jobs": 55
  },
  {
    "company_name": "Hut 8",
    "board_token": "hut8",
    "fresh_jobs": 55
  },
  {
    "company_name": "Levio",
    "board_token": "levio",
    "fresh_jobs": 55
  },
  {
    "company_name": "mindsquare AG",
    "board_token": "mindsquareag",
    "fresh_jobs": 55
  },
  {
    "company_name": "Red Ventures",
    "board_token": "redventures",
    "fresh_jobs": 55
  },
  {
    "company_name": "Stratolaunch",
    "board_token": "stratolaunch",
    "fresh_jobs": 55
  },
  {
    "company_name": "Banyan Software",
    "board_token": "banyansoftware",
    "fresh_jobs": 54
  },
  {
    "company_name": "Brunswick Group",
    "board_token": "brunswickgroup",
    "fresh_jobs": 54
  },
  {
    "company_name": "Dragos",
    "board_token": "dragos",
    "fresh_jobs": 54
  },
  {
    "company_name": "Electrosoft",
    "board_token": "electrosoft",
    "fresh_jobs": 54
  },
  {
    "company_name": "Ernesta",
    "board_token": "ernesta",
    "fresh_jobs": 54
  },
  {
    "company_name": "Forgen",
    "board_token": "forgen",
    "fresh_jobs": 54
  },
  {
    "company_name": "Metro Vein Centers",
    "board_token": "metroveincenters",
    "fresh_jobs": 54
  },
  {
    "company_name": "3 Day Blinds (Sales)",
    "board_token": "3dayblindssales",
    "fresh_jobs": 53
  },
  {
    "company_name": "Code and Theory",
    "board_token": "codeandtheory",
    "fresh_jobs": 53
  },
  {
    "company_name": "Heart + Paw",
    "board_token": "heartpaw",
    "fresh_jobs": 53
  },
  {
    "company_name": "Hillel International",
    "board_token": "hillel",
    "fresh_jobs": 53
  },
  {
    "company_name": "Hydrite",
    "board_token": "hydritechemicalco",
    "fresh_jobs": 53
  },
  {
    "company_name": "Lighthouse",
    "board_token": "lighthouse",
    "fresh_jobs": 53
  },
  {
    "company_name": "Neo4j",
    "board_token": "neo4j",
    "fresh_jobs": 53
  },
  {
    "company_name": "New Relic",
    "board_token": "newrelic",
    "fresh_jobs": 53
  },
  {
    "company_name": "Redstone Residential",
    "board_token": "redstoneresidential",
    "fresh_jobs": 53
  },
  {
    "company_name": "Viral Nation Inc.",
    "board_token": "viralnation",
    "fresh_jobs": 53
  },
  {
    "company_name": "Apex Companies - CSW",
    "board_token": "apexcompaniescsw",
    "fresh_jobs": 52
  },
  {
    "company_name": "Cision",
    "board_token": "cision",
    "fresh_jobs": 52
  },
  {
    "company_name": "Gatik AI",
    "board_token": "gatikaiinc",
    "fresh_jobs": 52
  },
  {
    "company_name": "Growe Talents",
    "board_token": "growetalents",
    "fresh_jobs": 52
  },
  {
    "company_name": "Kinder's",
    "board_token": "kinders",
    "fresh_jobs": 52
  },
  {
    "company_name": "Optimal Care",
    "board_token": "optimalcare",
    "fresh_jobs": 52
  },
  {
    "company_name": "Qualtrics",
    "board_token": "qualtrics",
    "fresh_jobs": 52
  },
  {
    "company_name": "Wing",
    "board_token": "wing",
    "fresh_jobs": 52
  },
  {
    "company_name": "ACT Power Services",
    "board_token": "actpowerservices",
    "fresh_jobs": 51
  },
  {
    "company_name": "Behavox",
    "board_token": "behavox",
    "fresh_jobs": 51
  },
  {
    "company_name": "fairlife",
    "board_token": "fairlife",
    "fresh_jobs": 51
  },
  {
    "company_name": "ID.me",
    "board_token": "idme",
    "fresh_jobs": 51
  },
  {
    "company_name": "Similarweb",
    "board_token": "similarweb",
    "fresh_jobs": 51
  },
  {
    "company_name": "Space Kinetic",
    "board_token": "spacekinetic",
    "fresh_jobs": 51
  },
  {
    "company_name": "SpotHopper",
    "board_token": "spothopper",
    "fresh_jobs": 51
  },
  {
    "company_name": "Talkspace Psychiatry",
    "board_token": "talkspacepsychiatry",
    "fresh_jobs": 51
  },
  {
    "company_name": "Thoughtworks",
    "board_token": "thoughtworks",
    "fresh_jobs": 51
  },
  {
    "company_name": "Vaxcyte",
    "board_token": "vaxcyte",
    "fresh_jobs": 51
  },
  {
    "company_name": "ClassPass",
    "board_token": "classpass",
    "fresh_jobs": 50
  },
  {
    "company_name": "Greenpoint Technologies",
    "board_token": "greenpointtechnologies",
    "fresh_jobs": 50
  },
  {
    "company_name": "Lightning AI",
    "board_token": "lightningai",
    "fresh_jobs": 50
  },
  {
    "company_name": "LVT",
    "board_token": "liveviewtechnologiesinc",
    "fresh_jobs": 50
  },
  {
    "company_name": "M9 Solutions",
    "board_token": "m9solutions",
    "fresh_jobs": 50
  },
  {
    "company_name": "Quest Defense Systems & Solutions, Inc.",
    "board_token": "questdefensesystemssolutionsinc",
    "fresh_jobs": 50
  },
  {
    "company_name": "Revlon Corporate",
    "board_token": "revloncorporate",
    "fresh_jobs": 50
  },
  {
    "company_name": "Thunes",
    "board_token": "thunes",
    "fresh_jobs": 50
  },
  {
    "company_name": "YipitData",
    "board_token": "yipitdata",
    "fresh_jobs": 50
  },
  {
    "company_name": "AKQA",
    "board_token": "akqa",
    "fresh_jobs": 49
  },
  {
    "company_name": "Awin",
    "board_token": "awin",
    "fresh_jobs": 49
  },
  {
    "company_name": "BILL",
    "board_token": "billcom",
    "fresh_jobs": 49
  },
  {
    "company_name": "Glance",
    "board_token": "glance",
    "fresh_jobs": 49
  },
  {
    "company_name": "Parloa",
    "board_token": "parloa",
    "fresh_jobs": 49
  },
  {
    "company_name": "Secretariat",
    "board_token": "secretariatadvisorsllc",
    "fresh_jobs": 49
  },
  {
    "company_name": "Sotheby's",
    "board_token": "sothebys",
    "fresh_jobs": 49
  },
  {
    "company_name": "Strive Health",
    "board_token": "strivehealth",
    "fresh_jobs": 49
  },
  {
    "company_name": "YipitData (Alternative)",
    "board_token": "yipitdatajobs",
    "fresh_jobs": 49
  },
  {
    "company_name": "AlphaSense India",
    "board_token": "alphasenseindia",
    "fresh_jobs": 48
  },
  {
    "company_name": "BDA",
    "board_token": "bdainc",
    "fresh_jobs": 48
  },
  {
    "company_name": "Evergreen Residential Holdings, LLC",
    "board_token": "evergreenresidentialemployeeservicescorp",
    "fresh_jobs": 48
  },
  {
    "company_name": "Latitude AI",
    "board_token": "latitude",
    "fresh_jobs": 48
  },
  {
    "company_name": "Skin Laundry",
    "board_token": "skinlaundry",
    "fresh_jobs": 48
  },
  {
    "company_name": "Talkdesk",
    "board_token": "talkdesk2",
    "fresh_jobs": 48
  },
  {
    "company_name": "Vulcan Elements",
    "board_token": "vulcanelements",
    "fresh_jobs": 48
  },
  {
    "company_name": "Acadia Pharmaceuticals Inc.",
    "board_token": "acadiapharmaceuticals",
    "fresh_jobs": 47
  },
  {
    "company_name": "Axle",
    "board_token": "axle",
    "fresh_jobs": 47
  },
  {
    "company_name": "CarGurus",
    "board_token": "cargurus",
    "fresh_jobs": 47
  },
  {
    "company_name": "Holistic Industries",
    "board_token": "holisticindustries",
    "fresh_jobs": 47
  },
  {
    "company_name": "LS3P",
    "board_token": "ls3p",
    "fresh_jobs": 47
  },
  {
    "company_name": "MiQ Digital",
    "board_token": "miqdigital",
    "fresh_jobs": 47
  },
  {
    "company_name": "Nex",
    "board_token": "nex",
    "fresh_jobs": 47
  },
  {
    "company_name": "RZR Global Inc.",
    "board_token": "rzr",
    "fresh_jobs": 47
  },
  {
    "company_name": "SK hynix America",
    "board_token": "skhynixamerica",
    "fresh_jobs": 47
  },
  {
    "company_name": "Strategic HR Client Job Openings",
    "board_token": "strategichr",
    "fresh_jobs": 47
  },
  {
    "company_name": "Tactile Medical",
    "board_token": "tactilemedical",
    "fresh_jobs": 47
  },
  {
    "company_name": "The Brattle Group",
    "board_token": "thebrattlegroup",
    "fresh_jobs": 47
  },
  {
    "company_name": "Woven Care",
    "board_token": "wovencare",
    "fresh_jobs": 47
  },
  {
    "company_name": "Zynga",
    "board_token": "zyngacareers",
    "fresh_jobs": 47
  },
  {
    "company_name": "Accordion",
    "board_token": "accordion",
    "fresh_jobs": 46
  },
  {
    "company_name": "Blockchain.com",
    "board_token": "blockchain",
    "fresh_jobs": 46
  },
  {
    "company_name": "BRPH",
    "board_token": "brph",
    "fresh_jobs": 46
  },
  {
    "company_name": "Catawiki",
    "board_token": "catawiki",
    "fresh_jobs": 46
  },
  {
    "company_name": "Exiger",
    "board_token": "exiger",
    "fresh_jobs": 46
  },
  {
    "company_name": "La Senza",
    "board_token": "lasenza",
    "fresh_jobs": 46
  },
  {
    "company_name": "National Lutheran Communities & Services",
    "board_token": "nationallutheraninc",
    "fresh_jobs": 46
  },
  {
    "company_name": "Olympus Property",
    "board_token": "olympusproperty",
    "fresh_jobs": 46
  },
  {
    "company_name": "Panthalassa",
    "board_token": "panthalassa",
    "fresh_jobs": 46
  },
  {
    "company_name": "Path Robotics",
    "board_token": "pathrobotics",
    "fresh_jobs": 46
  },
  {
    "company_name": "Sand Tech Holdings Limited",
    "board_token": "sandtechholdingslimited",
    "fresh_jobs": 46
  },
  {
    "company_name": "The Periscope Group",
    "board_token": "theperiscopegroup",
    "fresh_jobs": 46
  },
  {
    "company_name": "The Princeton Review",
    "board_token": "theprincetonreview",
    "fresh_jobs": 46
  },
  {
    "company_name": "Alpha Financial Markets Consulting",
    "board_token": "alphafmcroles",
    "fresh_jobs": 45
  },
  {
    "company_name": "Backbase",
    "board_token": "workatbackbase",
    "fresh_jobs": 45
  },
  {
    "company_name": "‎ConnectWise",
    "board_token": "connectwise",
    "fresh_jobs": 45
  },
  {
    "company_name": "Financial Times",
    "board_token": "financialtimes33",
    "fresh_jobs": 45
  },
  {
    "company_name": "Human Interest",
    "board_token": "humaninterest",
    "fresh_jobs": 45
  },
  {
    "company_name": "Northpoint Recovery Holdings, LLC",
    "board_token": "northpointrecoveryholdingsllc",
    "fresh_jobs": 45
  },
  {
    "company_name": "One Acre Fund",
    "board_token": "oneacrefund",
    "fresh_jobs": 45
  },
  {
    "company_name": "Oral Surgery Partners",
    "board_token": "oralsurgerypartners",
    "fresh_jobs": 45
  },
  {
    "company_name": "Quantum Space",
    "board_token": "quantumspacellc",
    "fresh_jobs": 45
  },
  {
    "company_name": "Sitreps",
    "board_token": "sitrepsllc",
    "fresh_jobs": 45
  },
  {
    "company_name": "Spaulding Ridge",
    "board_token": "spauldingridge",
    "fresh_jobs": 45
  },
  {
    "company_name": "Teneo external feed for LinkedIn",
    "board_token": "teneolinkedin",
    "fresh_jobs": 45
  },
  {
    "company_name": "Veo - Operations Careers",
    "board_token": "operationscareers",
    "fresh_jobs": 45
  },
  {
    "company_name": "Ambiq Micro, Inc.",
    "board_token": "ambiqmicroinc",
    "fresh_jobs": 44
  },
  {
    "company_name": "AppsFlyer",
    "board_token": "appsflyer",
    "fresh_jobs": 44
  },
  {
    "company_name": "AutoScout24",
    "board_token": "autoscout24",
    "fresh_jobs": 44
  },
  {
    "company_name": "Brainlabs",
    "board_token": "brainlabs",
    "fresh_jobs": 44
  },
  {
    "company_name": "Conga",
    "board_token": "conga",
    "fresh_jobs": 44
  },
  {
    "company_name": "Flex",
    "board_token": "flex",
    "fresh_jobs": 44
  },
  {
    "company_name": "Galaxy",
    "board_token": "galaxydigitalservices",
    "fresh_jobs": 44
  },
  {
    "company_name": "Genius Sports",
    "board_token": "geniussports",
    "fresh_jobs": 44
  },
  {
    "company_name": "GoFundMe",
    "board_token": "gofundme",
    "fresh_jobs": 44
  },
  {
    "company_name": "MG Properties",
    "board_token": "mgproperties",
    "fresh_jobs": 44
  },
  {
    "company_name": "Moloco",
    "board_token": "moloco",
    "fresh_jobs": 44
  },
  {
    "company_name": "MTC Care",
    "board_token": "meditelecare",
    "fresh_jobs": 44
  },
  {
    "company_name": "NewRocket",
    "board_token": "highmetric",
    "fresh_jobs": 44
  },
  {
    "company_name": "Revance",
    "board_token": "revance",
    "fresh_jobs": 44
  },
  {
    "company_name": "Stoke Space",
    "board_token": "stokespacetechnologies",
    "fresh_jobs": 44
  },
  {
    "company_name": "Wargaming",
    "board_token": "wargamingen",
    "fresh_jobs": 44
  },
  {
    "company_name": "Wonderschool",
    "board_token": "wonderschool",
    "fresh_jobs": 44
  },
  {
    "company_name": "Cloudbeds",
    "board_token": "cloudbeds",
    "fresh_jobs": 43
  },
  {
    "company_name": "CPI Security",
    "board_token": "cpisecurity",
    "fresh_jobs": 43
  },
  {
    "company_name": "CVX Ventures",
    "board_token": "cvx",
    "fresh_jobs": 43
  },
  {
    "company_name": "ENSCO, Inc.",
    "board_token": "ensco",
    "fresh_jobs": 43
  },
  {
    "company_name": "FirstMind",
    "board_token": "firstmind",
    "fresh_jobs": 43
  },
  {
    "company_name": "Gigs",
    "board_token": "gigs",
    "fresh_jobs": 43
  },
  {
    "company_name": "Ivalua",
    "board_token": "ivalua",
    "fresh_jobs": 43
  },
  {
    "company_name": "KBRA",
    "board_token": "krollbondratingagency",
    "fresh_jobs": 43
  },
  {
    "company_name": "Mirum Pharmaceuticals",
    "board_token": "mirumpharmaceuticals",
    "fresh_jobs": 43
  },
  {
    "company_name": "PhyNet Dermatology LLC (External)",
    "board_token": "phynetdermatology",
    "fresh_jobs": 43
  },
  {
    "company_name": "Precision AQ",
    "board_token": "precisionaq",
    "fresh_jobs": 43
  },
  {
    "company_name": "SonicWall",
    "board_token": "sonicwall",
    "fresh_jobs": 43
  },
  {
    "company_name": "Spire",
    "board_token": "spire",
    "fresh_jobs": 43
  },
  {
    "company_name": "Tanium",
    "board_token": "tanium",
    "fresh_jobs": 43
  },
  {
    "company_name": "Texas Car Title & Payday Loan Services, Inc",
    "board_token": "texascartitleandpaydayloanservicesinc",
    "fresh_jobs": 43
  },
  {
    "company_name": "Turf Masters Brands",
    "board_token": "turfmasters",
    "fresh_jobs": 43
  },
  {
    "company_name": "WorldStrides",
    "board_token": "world4822stri986des",
    "fresh_jobs": 43
  },
  {
    "company_name": "BEES",
    "board_token": "bees",
    "fresh_jobs": 42
  },
  {
    "company_name": "Betty",
    "board_token": "bettyjobboard",
    "fresh_jobs": 42
  },
  {
    "company_name": "Centria Healthcare",
    "board_token": "centriahealthcare",
    "fresh_jobs": 42
  },
  {
    "company_name": "Fora",
    "board_token": "foratravel",
    "fresh_jobs": 42
  },
  {
    "company_name": "i360technologies, Inc.",
    "board_token": "i360technologiesinc",
    "fresh_jobs": 42
  },
  {
    "company_name": "IEQ Capital",
    "board_token": "ieqcapital",
    "fresh_jobs": 42
  },
  {
    "company_name": "Jukebox Health",
    "board_token": "jukeboxhealth",
    "fresh_jobs": 42
  },
  {
    "company_name": "Landor",
    "board_token": "landor",
    "fresh_jobs": 42
  },
  {
    "company_name": "Major League Baseball",
    "board_token": "majorleaguebaseball",
    "fresh_jobs": 42
  },
  {
    "company_name": "May Mobility",
    "board_token": "maymobility",
    "fresh_jobs": 42
  },
  {
    "company_name": "PharmaCann",
    "board_token": "pharmacann",
    "fresh_jobs": 42
  },
  {
    "company_name": "phData",
    "board_token": "phdata",
    "fresh_jobs": 42
  }
] as const;

export const HUNDRED_THOUSAND_FLOOR_DISCOVERY_FRESH_JOBS = 60001;
